[project]
name = "face"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlib>=19.24.6",
    "flask>=3.0.3",
    "numpy>=2.1.3",
    "opencv-python>=4.10.0.84",
]
